# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'RogueIOSAndJava' do

pod 'Masonry'

end

target 'RogueIOSAndJavaTests' do

end

target 'RogueIOSAndJavaUITests' do

end

